name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libgl1-mesa-dev libegl1 libqt5x11extras5 ffmpeg xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install -r requirements.txt --no-cache-dir
          pip install faster-whisper==1.1.1 PyQt5==5.15.11 pytest av==12.3.0

      - name: List directory structure
        run: ls -R  # Debug: Verify file structure

      - name: Debug environment
        run: |
          python --version
          pip list
          pwd
          cat requirements.txt
          ffmpeg -version
          python -c "import av; print('av version:', av.__version__)"
          which xvfb-run  # Verify xvfb installation
        # Debug: Show environment details

      - name: Run unit tests
        env:
          ACTIONS_STEP_DEBUG: true  # Enable debug logging
        run: |
          xvfb-run python -m unittest discover -s tests -v